settings_version: 0.0.4
datasets_dir: /app/datasets
weights_dir: weights
runs_dir: runs
uuid: 0ae414ff41512f8ed10f8b80db709e68f6c23eaeb157180d14c9ce8d1f6e21ad
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
